version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/"
      - "/DbMcp.Tests"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      nuget-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      docker-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
